# Generated by Django 4.0.4 on 2022-06-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('goods', '0002_category_alter_good_options_alter_good_unit_of_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
