# Generated by Django 4.0.4 on 2022-06-01 14:45

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_category_managers_alter_good_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
